local p=game.Players.LocalPlayer
local h=p:WaitForChild("PlayerGui")
if h:FindFirstChild("StatHub")then h.StatHub:Destroy()end
local e=nil pcall(function() e=game:GetService("ReplicatedStorage"):FindFirstChild("Remotes") and game:GetService("ReplicatedStorage").Remotes:FindFirstChild("TesterRemote") end)
local function fire(a,b,c) if e then pcall(function() e:FireServer(a,b,c) end) end end
local gui=Instance.new("ScreenGui",h)gui.Name="StatHub"gui.ResetOnSpawn=false
local main=Instance.new("Frame",gui)main.Size=UDim2.new(0,600,0,420)main.Position=UDim2.new(0.5,-300,0.5,-210)main.BackgroundColor3=Color3.fromRGB(245,245,245)main.Active=true main.Draggable=true Instance.new("UICorner",main).CornerRadius=UDim.new(0,10)
local title=Instance.new("TextLabel",main)title.Size=UDim2.new(1,0,0,28)title.BackgroundColor3=Color3.fromRGB(22,22,22)title.Text="  STAT HUB • RightShift to hide"title.TextColor3=Color3.fromRGB(255,255,255)title.Font=Enum.Font.GothamBold title.TextSize=13 title.TextXAlignment=Enum.TextXAlignment.Left Instance.new("UICorner",title).CornerRadius=UDim.new(0,8)
local tabBar=Instance.new("Frame",main)tabBar.Size=UDim2.new(1,0,0,32)tabBar.Position=UDim2.new(0,0,0,30)tabBar.BackgroundTransparency=1
local content=Instance.new("Frame",main)content.Size=UDim2.new(1,-10,1,-75)content.Position=UDim2.new(0,5,0,65)content.BackgroundTransparency=1
local sBtn=Instance.new("TextButton",tabBar)sBtn.Size=UDim2.new(0.25,-5,1,0)sBtn.Position=UDim2.new(0,5,0,0)sBtn.BackgroundColor3=Color3.fromRGB(0,122,255)sBtn.Text="Stats"sBtn.TextColor3=Color3.new(1,1,1)Instance.new("UICorner",sBtn).CornerRadius=UDim.new(0,8)
local iBtn=Instance.new("TextButton",tabBar)iBtn.Size=UDim2.new(0.25,-5,1,0)iBtn.Position=UDim2.new(0.25,5,0,0)iBtn.BackgroundColor3=Color3.fromRGB(220,220,220)iBtn.Text="Items"Instance.new("UICorner",iBtn).CornerRadius=UDim.new(0,8)
local uBtn=Instance.new("TextButton",tabBar)uBtn.Size=UDim2.new(0.25,-5,1,0)uBtn.Position=UDim2.new(0.5,5,0,0)uBtn.BackgroundColor3=Color3.fromRGB(220,220,220)uBtn.Text="Unlocks"Instance.new("UICorner",uBtn).CornerRadius=UDim.new(0,8)
local setBtn=Instance.new("TextButton",tabBar)setBtn.Size=UDim2.new(0.25,-5,1,0)setBtn.Position=UDim2.new(0.75,5,0,0)setBtn.BackgroundColor3=Color3.fromRGB(220,220,220)setBtn.Text="Settings"Instance.new("UICorner",setBtn).CornerRadius=UDim.new(0,8)
local stats=Instance.new("Frame",content)stats.Name="Stats"stats.Size=UDim2.new(1,0,1,0)stats.BackgroundTransparency=1
local items=Instance.new("Frame",content)items.Name="Items"items.Size=UDim2.new(1,0,1,0)items.BackgroundTransparency=1 items.Visible=false
local unlocks=Instance.new("Frame",content)unlocks.Name="Unlocks"unlocks.Size=UDim2.new(1,0,1,0)unlocks.BackgroundTransparency=1 unlocks.Visible=false
local settings=Instance.new("Frame",content)settings.Name="Settings"settings.Size=UDim2.new(1,0,1,0)settings.BackgroundTransparency=1 settings.Visible=false
local function show(which) stats.Visible=which=="Stats" items.Visible=which=="Items" unlocks.Visible=which=="Unlocks" settings.Visible=which=="Settings" sBtn.BackgroundColor3=which=="Stats"and Color3.fromRGB(0,122,255)or Color3.fromRGB(220,220,220) iBtn.BackgroundColor3=which=="Items"and Color3.fromRGB(0,122,255)or Color3.fromRGB(220,220,220) uBtn.BackgroundColor3=which=="Unlocks"and Color3.fromRGB(0,122,255)or Color3.fromRGB(220,220,220) setBtn.BackgroundColor3=which=="Settings"and Color3.fromRGB(0,122,255)or Color3.fromRGB(220,220,220) end
sBtn.MouseButton1Click:Connect(function() show("Stats") end) iBtn.MouseButton1Click:Connect(function() show("Items") end) uBtn.MouseButton1Click:Connect(function() show("Unlocks") end) setBtn.MouseButton1Click:Connect(function() show("Settings") end)
-- STATS bright white boxes black text
local statNames={"STR","DEX","CON","INT","FTH","CHA","LCK"}
for i,s in ipairs(statNames)do local l=Instance.new("TextLabel",stats)l.Size=UDim2.new(0,50,0,28)l.Position=UDim2.new(0,10,0,10+(i-1)*36)l.BackgroundTransparency=1 l.Text=s l.TextColor3=Color3.fromRGB(0,0,0)l.Font=Enum.Font.GothamBold l.TextSize=14;local b=Instance.new("TextBox",stats)b.Name=s;b.Size=UDim2.new(0,100,0,28)b.Position=UDim2.new(0,60,0,10+(i-1)*34)b.BackgroundColor3=Color3.new(1,1,1)b.Text="9999"b.TextColor3=Color3.fromRGB(0,0,0)b.Font=Enum.Font.GothamBold b.TextSize=14 Instance.new("UICorner",b).CornerRadius=UDim.new(0,6) Instance.new("UIStroke",b).Color=Color3.fromRGB(0,0,0) end
local setAll=Instance.new("TextButton",stats)setAll.Size=UDim2.new(0,140,0,32)setAll.Position=UDim2.new(0,180,0,20)setAll.BackgroundColor3=Color3.fromRGB(0,122,255)setAll.Text="SET ALL 9999"setAll.TextColor3=Color3.new(1,1,1)setAll.Font=Enum.Font.GothamBold Instance.new("UICorner",setAll).CornerRadius=UDim.new(0,8)setAll.MouseButton1Click:Connect(function() for _,s in ipairs(statNames)do local b=stats:FindFirstChild(s) fire("SetStat",s,tonumber(b.Text) or 9999) task.wait(0.05) end end)
-- ITEMS bright + full list
local search=Instance.new("TextBox",items)search.Size=UDim2.new(1,-80,0,28)search.Position=UDim2.new(0,10,0,10)search.BackgroundColor3=Color3.new(1,1,1)search.PlaceholderText="search items..."search.TextColor3=Color3.fromRGB(0,0,0)search.Font=Enum.Font.GothamBold Instance.new("UICorner",search).CornerRadius=UDim.new(0,6)
local give=Instance.new("TextButton",items)give.Size=UDim2.new(0,70,0,28)give.Position=UDim2.new(1,-70,0,10)give.BackgroundColor3=Color3.fromRGB(0,122,255)give.Text="GIVE"give.TextColor3=Color3.new(1,1,1)Instance.new("UICorner",give).CornerRadius=UDim.new(0,6)
local iList=Instance.new("ScrollingFrame",items)iList.Size=UDim2.new(1,-20,1,-50)iList.Position=UDim2.new(0,10,0,45)iList.BackgroundColor3=Color3.fromRGB(230,230,230)iList.CanvasSize=UDim2.new(0,0,0,0)Instance.new("UICorner",iList).CornerRadius=UDim.new(0,8)Instance.new("UIListLayout",iList).Padding=UDim.new(0,4)
local allItems={}pcall(function() for k,v in pairs(require(game:GetService("ReplicatedStorage").Dictionaries.Items))do table.insert(allItems,k) end end)if #allItems<10 then allItems={"Sword in Stone","Giant's Greatsword","Healing Potion","Energy Potion","Summoning Star","Dragonite Chip","Gemstone","Ectoplasm","Whetstone","Honey Glazed Carp"} end table.sort(allItems)
local iBtns={}local function refreshItems() for _,b in ipairs(iBtns)do b:Destroy()end iBtns={} local f=search.Text:lower() for _,name in ipairs(allItems)do if f=="" or name:lower():find(f)then local b=Instance.new("TextButton",iList)b.Size=UDim2.new(1,-10,0,26)b.BackgroundColor3=Color3.new(1,1,1)b.Text=name;b.TextColor3=Color3.fromRGB(0,0,0)b.Font=Enum.Font.Gotham Instance.new("UICorner",b).CornerRadius=UDim.new(0,6)table.insert(iBtns,b)b.MouseButton1Click:Connect(function() search.Text=name end)end end iList.CanvasSize=UDim2.new(0,0,0,#iBtns*30)end search:GetPropertyChangedSignal("Text"):Connect(refreshItems)refreshItems() give.MouseButton1Click:Connect(function() if search.Text~="" then fire("GiveItem",search.Text,1) end end)
-- UNLOCKS 3 lists in one scroll: Achievements + Races + Outfits
local uSearch=Instance.new("TextBox",unlocks)uSearch.Size=UDim2.new(1,-90,0,26)uSearch.Position=UDim2.new(0,10,0,10)uSearch.BackgroundColor3=Color3.new(1,1,1)uSearch.PlaceholderText="search achievements / races / outfits..."uSearch.TextColor3=Color3.fromRGB(0,0,0)Instance.new("UICorner",uSearch).CornerRadius=UDim.new(0,6)
local uGo=Instance.new("TextButton",unlocks)uGo.Size=UDim2.new(0,80,0,26)uGo.Position=UDim2.new(1,-80,0,10)uGo.BackgroundColor3=Color3.fromRGB(0,122,255)uGo.Text="UNLOCK"uGo.TextColor3=Color3.new(1,1,1)Instance.new("UICorner",uGo).CornerRadius=UDim.new(0,6)
local uList=Instance.new("ScrollingFrame",unlocks)uList.Size=UDim2.new(1,-20,1,-50)uList.Position=UDim2.new(0,10,0,45)uList.BackgroundColor3=Color3.fromRGB(230,230,230)Instance.new("UICorner",uList).CornerRadius=UDim.new(0,8)Instance.new("UIListLayout",uList).Padding=UDim.new(0,4)
local achs,races,outs={}, {}, {} pcall(function() for k,v in pairs(require(game:GetService("ReplicatedStorage").Dictionaries.Achievements))do table.insert(achs,k) end end) pcall(function() for k,v in pairs(require(game:GetService("ReplicatedStorage").Dictionaries.Races))do if k~="Order" then table.insert(races,k) end end end) pcall(function() for k,v in pairs(require(game:GetService("ReplicatedStorage").Dictionaries.Outfits))do table.insert(outs,k) end end)
if #achs==0 then achs={"Gigantomachy","Ultraviolence","A Small Favor","Hero of Elfkin"} end
if #races==0 then races={"Human","Elf","Dwarf","Kobold","Lunaeia","Withered"} end
if #outs==0 then outs={"Adventurer","Wandering Maiden","Veteran Armor","Monk Robes"} end
table.sort(achs) table.sort(races) table.sort(outs)
local combined={}for _,a in ipairs(achs)do table.insert(combined,"[ACH] "..a) end for _,r in ipairs(races)do table.insert(combined,"[RACE] "..r) end for _,o in ipairs(outs)do table.insert(combined,"[OUTFIT] "..o) end
local uBtns={}
local function refreshU() for _,b in ipairs(uBtns)do b:Destroy() end uBtns={} local f=uSearch.Text:lower() for _,name in ipairs(combined)do if f=="" or name:lower():find(f)then local tag=name:sub(1,6) local col=tag=="[ACH] " and Color3.fromRGB(255,230,150) or tag=="[RACE]" and Color3.fromRGB(180,220,255) or Color3.fromRGB(200,255,180) local b=Instance.new("TextButton",uList)b.Size=UDim2.new(1,-10,0,24)b.BackgroundColor3=Color3.new(1,1,1)b.Text=name;b.TextColor3=Color3.fromRGB(0,0,0)b.Font=Enum.Font.Gotham Instance.new("UICorner",b).CornerRadius=UDim.new(0,6)local c=Instance.new("Frame",b)c.Size=UDim2.new(0,6,1,0)c.BackgroundColor3=col Instance.new("UICorner",c).CornerRadius=UDim.new(0,6) table.insert(uBtns,b) b.MouseButton1Click:Connect(function() uSearch.Text=name:gsub("%[.-%] ","") end) end end uList.CanvasSize=UDim2.new(0,0,0,#uBtns*28) end
uSearch:GetPropertyChangedSignal("Text"):Connect(refreshU)refreshU()
uGo.MouseButton1Click:Connect(function() local n=uSearch.Text if n=="" then return end fire("SetAchievement",n,true) fire("GiveItem",n,1) end)
-- SETTINGS
local rebind=Instance.new("TextButton",settings)rebind.Size=UDim2.new(1,-20,0,36)rebind.Position=UDim2.new(0,10,0,20)rebind.BackgroundColor3=Color3.new(1,1,1)rebind.TextColor3=Color3.fromRGB(0,0,0)rebind.Text="Toggle Key: RightShift (Click to rebind)"rebind.Font=Enum.Font.GothamBold Instance.new("UICorner",rebind).CornerRadius=UDim.new(0,8)
local waiting=false;local toggleKey=Enum.KeyCode.RightShift;rebind.MouseButton1Click:Connect(function() waiting=true rebind.Text="Press any key..." end)game:GetService("UserInputService").InputBegan:Connect(function(input,gp) if waiting and input.KeyCode~=Enum.KeyCode.Unknown then toggleKey=input.KeyCode rebind.Text="Bound: "..toggleKey.Name title.Text="  stat hub • "..toggleKey.Name.." to hide" waiting=false return end if not gp and input.KeyCode==toggleKey then gui.Enabled=not gui.Enabled end end)
print("pickler! bright hub loaded")
